name: Deploy MAYA Web (GitHub Pages)

# Har push par automatically deploy ho jayega
on:
  push:
    branches: [main, master]
  workflow_dispatch: # manually bhi chala sakte ho

# permissions chahiye GitHub Pages ke liye
permissions:
  contents: read
  pages: write
  id-token: write

# ek hi deploy chalne do ek saath
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 1. Code checkout
        uses: actions/checkout@v4

      - name: 2. Setup Pages
        uses: actions/configure-pages@v5

      - name: 3. Upload artifact (public folder)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: 4. Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
